site_name: Via

nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - Configuration and routing: configuration.md
  - Architecture: architecture.md
  - Development and benchmarking: development.md

theme:
  name: readthedocs
